### PR TITLE
Credit info

### PR DESCRIPTION
**Pull request by EvanBarbour3**
## Features
- Added `getCreditInformation` documentation for an `Application`

### CODE REVIEW

**Comment by EvanBarbour3** [comment]
@00eadeyemi can you look at this before Woj does?

**Comment by 00eadeyemi** [comment]
@EvanBarbour3 checked and can see that everything works.

**Comment by EvanBarbour3** [comment]
@wnowicki I would not merge this until everything is released?

**Comment by wnowicki** [comment]
- OK
- This needs to wait for the release

**Pull request merged**
